/* 
 *   _____ _______         _                      _
 *  |_   _|__   __|       | |                    | |
 *    | |    | |_ __   ___| |___      _____  _ __| | __  ___ ____
 *    | |    | | '_ \ / _ \ __\ \ /\ / / _ \| '__| |/ / / __|_  /
 *   _| |_   | | | | |  __/ |_ \ V  V / (_) | |  |   < | (__ / /
 *  |_____|  |_|_| |_|\___|\__| \_/\_/ \___/|_|  |_|\_(_)___/___|
 *                                 _
 *               ___ ___ ___ _____|_|_ _ _____
 *              | . |  _| -_|     | | | |     |  LICENCE
 *              |  _|_| |___|_|_|_|_|___|_|_|_|
 *              |_|
 * 
 *  IT ZPRAVODAJSTVÍ  <>  PROGRAMOVÁNÍ  <>  HW A SW  <>  KOMUNITA
 * 
 *  Tento zdrojový kód je součástí výukových seriálů na
 *  IT sociální síti WWW.ITNETWORK.CZ
 * 
 *  Kód spadá pod licenci prémiového obsahu a vznikl díky podpoře
 *  našich členů. Je určen pouze pro osobní užití a nesmí být šířen.
 *  Více informací na http://www.itnetwork.cz/licence
 */
package cisla;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author bad-fox
 */
public class HlavniJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HlavnyJFrame
     */
    public HlavniJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poradieJComboBox = new javax.swing.JComboBox<>();
        vstupJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vypocitejJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        zerazenyJLabel = new javax.swing.JLabel();
        prumerJLabel = new javax.swing.JLabel();
        nejvetsiJLabel = new javax.swing.JLabel();
        nejmensiJLabel = new javax.swing.JLabel();
        soucetJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Statistiky");

        poradieJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "od nejmenšího po největší", "od největšího po nejmenší" }));

        jLabel1.setText("Zadej celá čísla:");

        jLabel2.setText("Seřadit podle:");

        vypocitejJButton.setText("Vypočítej");
        vypocitejJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vypocitejJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Součet čísel:");

        jLabel4.setText("Nejmenší číslo:");

        jLabel5.setText("Největší číslo:");

        jLabel6.setText("Průměr čísel:");

        jLabel7.setText("Seřazená podle velikosti:");

        zerazenyJLabel.setText("0");

        prumerJLabel.setText("0");

        nejvetsiJLabel.setText("0");

        nejmensiJLabel.setText("0");

        soucetJLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vstupJTextField)
                            .addComponent(poradieJComboBox, 0, 440, Short.MAX_VALUE)
                            .addComponent(vypocitejJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nejmensiJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nejvetsiJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prumerJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zerazenyJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soucetJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(vstupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poradieJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(vypocitejJButton)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(soucetJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nejmensiJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nejvetsiJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(prumerJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zerazenyJLabel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vypocitejJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vypocitejJButtonActionPerformed
        // TODO add your handling code here:
        // vytvaranie premennych
        String text = vstupJTextField.getText();
        String vstup[] = text.split(" ");
        List<Integer> cisla = new ArrayList<>();
        int nejmensi = 0;
        int nejvetsi = 0;
        int soucet = 0;
        double prumer = 0;
        String serazenyText = "";

        //logika
        //parsovani stringu na int
        for (String s : vstup) {
            int cislo = Integer.parseInt(s);
            cisla.add(cislo);
            soucet += cislo;
        }

        Collections.sort(cisla);
        nejmensi = cisla.get(0);
        nejvetsi = cisla.get(cisla.size() - 1);
        prumer = (double) soucet / (double) cisla.size();

        if (poradieJComboBox.getSelectedIndex() == 1) { // řazení je pozpátku
            Collections.reverse(cisla);
        }
        for (int i : cisla) {
            serazenyText += i + " ";
        }

        //dosadenie hodnot do JLabelov
        zerazenyJLabel.setText(serazenyText);
        nejmensiJLabel.setText(String.valueOf(nejmensi));
        nejvetsiJLabel.setText(String.valueOf(nejvetsi));
        prumerJLabel.setText(String.valueOf(prumer));
        soucetJLabel.setText(String.valueOf(soucet));
    }//GEN-LAST:event_vypocitejJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavniJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //prepisujem framelocation, aby sa okno zobrazilo na strede obrazovky
                HlavniJFrame frame = new HlavniJFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nejmensiJLabel;
    private javax.swing.JLabel nejvetsiJLabel;
    private javax.swing.JComboBox<String> poradieJComboBox;
    private javax.swing.JLabel prumerJLabel;
    private javax.swing.JLabel soucetJLabel;
    private javax.swing.JTextField vstupJTextField;
    private javax.swing.JButton vypocitejJButton;
    private javax.swing.JLabel zerazenyJLabel;
    // End of variables declaration//GEN-END:variables
}
